# Netlify configuration
title = "Local Loop Merseyside"
baseURL = "https://main--llm-june-2024.netlify.app/" #YOUR SITE URL

[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"



